name: Starskey CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Run bloom filter tests
        run: go test ./bloomfilter -v

      - name: Run pager tests
        run: go test ./pager -v

      - name: Run ttree tests
        run: go test ./ttree -v

      - name: Run surf tests
        run: go test ./surf -v

      - name: Run core tests
        run: go test -v